import resend
from app.config import settings
from app.utils.logger import get_logger

logger = get_logger("email_service")

# Real department email mapping — used to resolve AI-generated "to" team names
# to actual email addresses for dispatch.
DEPT_EMAIL_MAP = {
    "strategic oversight": "johnphilji2007@gmail.com",
    "operations": "chriscric17@gmail.com",
    "risk & audit": "armaansyed009@gmail.com",
    "risk and audit": "armaansyed009@gmail.com",
    "compliance": "johnphilji2007@gmail.com",
}

class EmailService:
    def __init__(self):
        if settings.RESEND_API_KEY:
            resend.api_key = settings.RESEND_API_KEY
        else:
            logger.warning("RESEND_API_KEY not found. Email service will run in MOCK mode.")

    async def send_compliance_alert(
        self,
        to_email: str | None = None,
        to_name: str | None = None,
        subject: str = "Regulatory Compliance Update",
        body: str = "",
        body_markdown: str = "",
    ):
        """Send a personalized compliance alert email.
        
        Accepts either to_email directly, or to_name which gets resolved
        to a real email address from the department mapping.
        """
        # Resolve destination email
        actual_email = to_email
        if not actual_email and to_name:
            actual_email = DEPT_EMAIL_MAP.get(to_name.lower().strip())
        if not actual_email:
            actual_email = "johnphilji2007@gmail.com"  # Fallback

        # Resolve body content
        actual_body = body_markdown or body or "No content."

        if not settings.RESEND_API_KEY:
            logger.info("[MOCK EMAIL] To: %s (%s) | Subject: %s", to_name or "Team", actual_email, subject)
            return True

        try:
            params = {
                "from": "Swarm AI <onboarding@resend.dev>",
                "to": actual_email,
                "subject": subject,
                "html": f"<div style='font-family:monospace;padding:20px;'>"
                        f"<h2 style='color:#0066FF;'>🤖 Swarm AI — Compliance Intelligence</h2>"
                        f"<p><strong>Department:</strong> {to_name or 'Compliance Team'}</p>"
                        f"<hr/>"
                        f"<div style='white-space:pre-wrap;line-height:1.6;'>{actual_body}</div>"
                        f"<hr/>"
                        f"<p style='font-size:10px;color:#888;'>Auto-generated by Swarm AI Autonomous Compliance Engine</p>"
                        f"</div>",
            }
            result = resend.Emails.send(params)
            logger.info("✅ Email sent to %s (%s) — ID: %s", to_name or "Team", actual_email, result)
            return True
        except Exception as exc:
            logger.error("❌ Failed to send email to %s (%s): %s", to_name or "Team", actual_email, exc)
            return False

_service = None

def get_email_service() -> EmailService:
    global _service
    if _service is None:
        _service = EmailService()
    return _service
