import sib_api_v3_sdk
from sib_api_v3_sdk.rest import ApiException
from app.config import settings
from app.utils.logger import get_logger

logger = get_logger("email_service")

# Real department email mapping — used for display in the UI and routing.
DEPT_EMAIL_MAP = {
    "strategic oversight": "johnphilji2007@gmail.com",
    "operations": "chriscric17@gmail.com",
    "risk & audit": "armaansyed009@gmail.com",
    "risk and audit": "armaansyed009@gmail.com",
    "compliance": "johnphilji2007@gmail.com",
}


def _build_email_html(to_name: str, subject: str, body: str) -> str:
    """Build a professional, convincing HTML email template."""
    # Detect severity from subject line
    severity_color = "#0066FF"
    severity_label = "INFO"
    if "🔴" in subject or "URGENT" in subject or "CRITICAL" in subject:
        severity_color = "#FF4D4D"
        severity_label = "HIGH SEVERITY"
    elif "⚠️" in subject or "ACTION" in subject:
        severity_color = "#FFA500"
        severity_label = "ACTION REQUIRED"

    # Convert newlines to HTML breaks for body
    body_html = body.replace("\n", "<br/>")

    return f"""
    <div style="font-family: 'Segoe UI', -apple-system, sans-serif; max-width: 680px; margin: 0 auto; background: #FFFEF2; border: 3px solid #0A0A0A; box-shadow: 8px 8px 0px #0A0A0A;">
        <!-- Header -->
        <div style="background: #0A0A0A; color: #FFFEF2; padding: 24px 28px;">
            <div style="display: flex; align-items: center; gap: 12px;">
                <div style="font-size: 28px;">🤖</div>
                <div>
                    <h1 style="margin: 0; font-size: 20px; font-weight: 900; letter-spacing: -0.5px; text-transform: uppercase;">
                        Swarm AI — Compliance Intelligence
                    </h1>
                    <p style="margin: 4px 0 0 0; font-size: 10px; color: #888; text-transform: uppercase; letter-spacing: 2px;">
                        Autonomous Multi-Agent Regulatory Analysis Engine
                    </p>
                </div>
            </div>
        </div>

        <!-- Severity Banner -->
        <div style="background: {severity_color}; color: white; padding: 10px 28px; font-size: 11px; font-weight: 800; text-transform: uppercase; letter-spacing: 1.5px;">
            ⚡ {severity_label} — AUTONOMOUS AI ALERT
        </div>

        <!-- Recipient Info -->
        <div style="padding: 20px 28px 0 28px; border-bottom: 2px dashed #DDD;">
            <table style="width: 100%; font-size: 12px; color: #555;">
                <tr>
                    <td style="padding: 4px 0;"><strong style="color: #0A0A0A;">TO:</strong> {to_name}</td>
                </tr>
                <tr>
                    <td style="padding: 4px 0;"><strong style="color: #0A0A0A;">SUBJECT:</strong> {subject}</td>
                </tr>
                <tr>
                    <td style="padding: 4px 0 12px 0;"><strong style="color: #0A0A0A;">GENERATED BY:</strong> Llama 3.2 → Swarm AI Agent Pipeline</td>
                </tr>
            </table>
        </div>

        <!-- Body -->
        <div style="padding: 24px 28px; font-size: 13px; line-height: 1.7; color: #1A1A1A;">
            {body_html}
        </div>

        <!-- Footer -->
        <div style="background: #F5F0E8; border-top: 3px solid #0A0A0A; padding: 16px 28px;">
            <div style="display: flex; align-items: center; gap: 16px;">
                <div style="flex: 1;">
                    <p style="margin: 0; font-size: 9px; color: #888; text-transform: uppercase; letter-spacing: 1px; line-height: 1.6;">
                        This email was autonomously generated by Swarm AI's multi-agent compliance intelligence engine.<br/>
                        Pipeline: Source Monitor → Document Extractor → Change Detector → Impact Mapper → Report Generator → Validator<br/>
                        Model: Llama 3.2 (8B) via Ollama | Embeddings: nomic-embed-text | Vector Store: ChromaDB
                    </p>
                </div>
            </div>
            <div style="margin-top: 12px; padding-top: 8px; border-top: 1px solid #DDD;">
                <p style="margin: 0; font-size: 8px; color: #AAA; text-transform: uppercase; letter-spacing: 1px;">
                    © 2024 Swarm AI — Autonomous Compliance & Regulatory Intelligence System | SunHacks 2024
                </p>
            </div>
        </div>
    </div>
    """


class EmailService:
    def __init__(self):
        self.api_instance = None
        if settings.BREVO_API_KEY:
            configuration = sib_api_v3_sdk.Configuration()
            configuration.api_key['api-key'] = settings.BREVO_API_KEY
            self.api_instance = sib_api_v3_sdk.TransactionalEmailsApi(sib_api_v3_sdk.ApiClient(configuration))
            logger.info("Brevo API initialized. Sender: %s", settings.BREVO_SENDER_EMAIL)
        else:
            logger.warning("BREVO_API_KEY not found. Email service will run in MOCK mode.")

    async def send_compliance_alert(
        self,
        to_email: str | None = None,
        to_name: str | None = None,
        subject: str = "Regulatory Compliance Update",
        body: str = "",
        body_markdown: str = "",
    ) -> bool:
        """Send a personalized compliance alert email via Brevo.
        
        This sends to the ACTUAL recipient provided, enabling real
        team-wide notifications.
        """
        display_name = to_name or "Compliance Team"
        actual_body = body_markdown or body or "No content."
        
        # Resolve destination email
        actual_email = to_email
        if not actual_email and to_name:
            actual_email = DEPT_EMAIL_MAP.get(to_name.lower().strip())
        
        if not actual_email:
            actual_email = settings.BREVO_SENDER_EMAIL # Fallback to sender

        if not self.api_instance:
            logger.info("[MOCK EMAIL] To: %s (%s) | Subject: %s", display_name, actual_email, subject)
            return True

        try:
            html_content = _build_email_html(display_name, subject, actual_body)
            
            send_smtp_email = sib_api_v3_sdk.SendSmtpEmail(
                to=[{"email": actual_email, "name": display_name}],
                html_content=html_content,
                subject=subject,
                sender={"name": settings.BREVO_SENDER_NAME, "email": settings.BREVO_SENDER_EMAIL}
            )
            
            api_response = self.api_instance.send_transac_email(send_smtp_email)
            logger.info("Email sent for [%s] -> %s -- MsgID: %s", display_name, actual_email, api_response.message_id)
            return True
        except ApiException as e:
            logger.error("Exception when calling TransactionalEmailsApi->send_transac_email: %s", e)
            return False
        except Exception as exc:
            logger.error("Failed to send email for [%s]: %s", display_name, exc)
            return False

_service = None

def get_email_service() -> EmailService:
    global _service
    if _service is None:
        _service = EmailService()
    return _service
